<a href="https://colab.research.google.com/github/maliha-crypto/emptyrepository/blob/main/Maliha_Rahman_DSRP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Repository + upload the data set
df = pd.read_csv("health_and_nutrition_combined_clean.csv")
df.head()

,Unnamed: 0,SEQN,RIAGENDR,RIDRETH3,RIDAGEYR,BMXHT,BMXBMI,BMXWT,RIDEXPRG,WTMEC4YR
0,0,83732,1,3,62,1845.0,27.8,94.8,NaN,NaN
1,1,83733,1,3,53,1714.0,30.8,90.4,NaN,NaN
2,2,83734,1,3,78,1701.0,28.8,83.4,NaN,NaN
3,3,83741,1,4,22,1654.0,28.0,76.6,NaN,NaN
4,4,83744,1,4,56,1794.0,33.6,108.3,NaN,NaN

In [ ]:
# Change the Column names
# Change the codes to what they actually represent
# Drop uneccesary columns
# Check misisng values/data

In [5]:
# Rename the columns
df = df.rename(columns = {
    "SEQN": "Participant ID",
    "RIAGENDR": "Gender",
    "RIDRETH3": "Race Ethnicity",
    "RIDAGEYR": "Age",
    "BMXHT": "Height",
    "BMXBMI": "BMI",
    "BMXWT": "Weight",
    "RIDEXPRG": "Pregnancy Status",
    "WTMEC4YR": "Survey Weight"
})
df.columns

Index(['Unnamed: 0', 'Participant ID', 'Gender', 'Race Ethnicity', 'Age',
       'Height', 'BMI', 'Weight', 'Pregnancy Status', 'Survey Weight'],
      dtype='object')

In [6]:
# Drop the "Unnamed: 0" column
df = df.drop(columns=["Unnamed: 0"])
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,1,3,62,1845.0,27.8,94.8,NaN,NaN
1,83733,1,3,53,1714.0,30.8,90.4,NaN,NaN
2,83734,1,3,78,1701.0,28.8,83.4,NaN,NaN
3,83741,1,4,22,1654.0,28.0,76.6,NaN,NaN
4,83744,1,4,56,1794.0,33.6,108.3,NaN,NaN

In [8]:
# Change the codes to what they actually mean, gender
df["Gender"] = df["Gender"].replace({1: "Male", 2: "Female"})
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,Male,3,62,1845.0,27.8,94.8,NaN,NaN
1,83733,Male,3,53,1714.0,30.8,90.4,NaN,NaN
2,83734,Male,3,78,1701.0,28.8,83.4,NaN,NaN
3,83741,Male,4,22,1654.0,28.0,76.6,NaN,NaN
4,83744,Male,4,56,1794.0,33.6,108.3,NaN,NaN

In [9]:
# Now same thing for "Race Ethnicity"
# Check which ones are actually used in the dataset
df["Race Ethnicity"].unique()

array([3, 4, 7, 6, 1])

In [11]:
df["Race Ethnicity"] = df["Race Ethnicity"].replace({
    1: "Mexican American",
    3: "Non-Hispanic White",
    4: "Non-Hispanic Black",
    6: "Non-Hispanic Asian",
    7: "Other Race, Including Multiracial"
})
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,Male,Non-Hispanic White,62,1845.0,27.8,94.8,NaN,NaN
1,83733,Male,Non-Hispanic White,53,1714.0,30.8,90.4,NaN,NaN
2,83734,Male,Non-Hispanic White,78,1701.0,28.8,83.4,NaN,NaN
3,83741,Male,Non-Hispanic Black,22,1654.0,28.0,76.6,NaN,NaN
4,83744,Male,Non-Hispanic Black,56,1794.0,33.6,108.3,NaN,NaN

In [12]:
# Check NaNs
df.isnull().sum()

Participant ID          0
Gender                  0
Race Ethnicity          0
Age                     0
Height                136
BMI                   157
Weight                143
Pregnancy Status     8442
Survey Weight       10614
dtype: int64

In [13]:
# Drop "Survey Weight"
df = df.drop(columns=["Survey Weight"])
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status
0,83732,Male,Non-Hispanic White,62,1845.0,27.8,94.8,NaN
1,83733,Male,Non-Hispanic White,53,1714.0,30.8,90.4,NaN
2,83734,Male,Non-Hispanic White,78,1701.0,28.8,83.4,NaN
3,83741,Male,Non-Hispanic Black,22,1654.0,28.0,76.6,NaN
4,83744,Male,Non-Hispanic Black,56,1794.0,33.6,108.3,NaN