<a href="https://colab.research.google.com/github/maliha-crypto/emptyrepository/blob/main/Maliha_Rahman_DSRP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
# Repository + upload the data set
df = pd.read_csv("health_and_nutrition_combined_clean.csv")
df.head()

,Unnamed: 0,SEQN,RIAGENDR,RIDRETH3,RIDAGEYR,BMXHT,BMXBMI,BMXWT,RIDEXPRG,WTMEC4YR
0,0,83732,1,3,62,1845.0,27.8,94.8,NaN,NaN
1,1,83733,1,3,53,1714.0,30.8,90.4,NaN,NaN
2,2,83734,1,3,78,1701.0,28.8,83.4,NaN,NaN
3,3,83741,1,4,22,1654.0,28.0,76.6,NaN,NaN
4,4,83744,1,4,56,1794.0,33.6,108.3,NaN,NaN

In [7]:
# Change the Column names
# Change the codes to what they actually represent
# Drop uneccesary columns
# Check misisng values/data

In [31]:
# Rename the columns
df = df.rename(columns = {
    "SEQN": "Participant ID",
    "RIAGENDR": "Gender",
    "RIDRETH3": "Race Ethnicity",
    "RIDAGEYR": "Age",
    "BMXHT": "Height",
    "BMXBMI": "BMI",
    "BMXWT": "Weight",
    "RIDEXPRG": "Pregnancy Status",
    "WTMEC4YR": "Survey Weight"
})
df.columns

Index(['Participant ID', 'Gender', 'Race Ethnicity', 'Age', 'Height', 'BMI',
       'Weight'],
      dtype='object')

In [8]:
# Drop the "Unnamed: 0" column
df = df.drop(columns=["Unnamed: 0"])
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,1,3,62,1845.0,27.8,94.8,NaN,NaN
1,83733,1,3,53,1714.0,30.8,90.4,NaN,NaN
2,83734,1,3,78,1701.0,28.8,83.4,NaN,NaN
3,83741,1,4,22,1654.0,28.0,76.6,NaN,NaN
4,83744,1,4,56,1794.0,33.6,108.3,NaN,NaN

In [9]:
# Change the codes to what they actually mean, gender
df["Gender"] = df["Gender"].replace({1: "Male", 2: "Female"})
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,Male,3,62,1845.0,27.8,94.8,NaN,NaN
1,83733,Male,3,53,1714.0,30.8,90.4,NaN,NaN
2,83734,Male,3,78,1701.0,28.8,83.4,NaN,NaN
3,83741,Male,4,22,1654.0,28.0,76.6,NaN,NaN
4,83744,Male,4,56,1794.0,33.6,108.3,NaN,NaN

In [10]:
# Now same thing for "Race Ethnicity"
# Check which ones are actually used in the dataset
df["Race Ethnicity"].unique()

array([3, 4, 7, 6, 1])

In [11]:
df["Race Ethnicity"] = df["Race Ethnicity"].replace({
    1: "Mexican American",
    3: "Non-Hispanic White",
    4: "Non-Hispanic Black",
    6: "Non-Hispanic Asian",
    7: "Other Race, Including Multiracial"
})
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status,Survey Weight
0,83732,Male,Non-Hispanic White,62,1845.0,27.8,94.8,NaN,NaN
1,83733,Male,Non-Hispanic White,53,1714.0,30.8,90.4,NaN,NaN
2,83734,Male,Non-Hispanic White,78,1701.0,28.8,83.4,NaN,NaN
3,83741,Male,Non-Hispanic Black,22,1654.0,28.0,76.6,NaN,NaN
4,83744,Male,Non-Hispanic Black,56,1794.0,33.6,108.3,NaN,NaN

In [12]:
# Check NaNs
df.isnull().sum()

Participant ID          0
Gender                  0
Race Ethnicity          0
Age                     0
Height                136
BMI                   157
Weight                143
Pregnancy Status     8442
Survey Weight       10614
dtype: int64

In [13]:
# Drop "Survey Weight"
df = df.drop(columns=["Survey Weight"])
df.head()

,Participant ID,Gender,Race Ethnicity,Age,Height,BMI,Weight,Pregnancy Status
0,83732,Male,Non-Hispanic White,62,1845.0,27.8,94.8,NaN
1,83733,Male,Non-Hispanic White,53,1714.0,30.8,90.4,NaN
2,83734,Male,Non-Hispanic White,78,1701.0,28.8,83.4,NaN
3,83741,Male,Non-Hispanic Black,22,1654.0,28.0,76.6,NaN
4,83744,Male,Non-Hispanic Black,56,1794.0,33.6,108.3,NaN

In [14]:
# Drop "Pregnancy Status"
df = df.drop(columns=["Pregnancy Status"])
df.head()

   Participant ID Gender      Race Ethnicity  Age  Height   BMI  Weight
0           83732   Male  Non-Hispanic White   62  1845.0  27.8    94.8
1           83733   Male  Non-Hispanic White   53  1714.0  30.8    90.4
2           83734   Male  Non-Hispanic White   78  1701.0  28.8    83.4
3           83741   Male  Non-Hispanic Black   22  1654.0  28.0    76.6
4           83744   Male  Non-Hispanic Black   56  1794.0  33.6   108.3

In [15]:
df.columns

Index(['Participant ID', 'Gender', 'Race Ethnicity', 'Age', 'Height', 'BMI',
       'Weight'],
      dtype='object')

In [16]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [17]:
# Check for missing values
df.isnull().sum()

Participant ID      0
Gender              0
Race Ethnicity      0
Age                 0
Height            136
BMI               157
Weight            143
dtype: int64

In [19]:
# Dropping the missing values in Height, BMI, and Weight
df = df.dropna()
df.isnull().sum()

Participant ID    0
Gender            0
Race Ethnicity    0
Age               0
Height            0
BMI               0
Weight            0
dtype: int64

In [20]:
# Check height and then fix it
df["Height"].describe()

count    10457.000000
mean      1662.120685
std        101.272075
min       1297.000000
25%       1587.000000
50%       1659.000000
75%       1736.000000
max       2027.000000
Name: Height, dtype: float64

In [22]:
df["Height"] = df["Height"] / 10
df["Height"].describe()

count    10457.000000
mean        16.621207
std          1.012721
min         12.970000
25%         15.870000
50%         16.590000
75%         17.360000
max         20.270000
Name: Height, dtype: float64

In [23]:
df.head()

   Participant ID Gender      Race Ethnicity  Age  Height   BMI  Weight
0           83732   Male  Non-Hispanic White   62   18.45  27.8    94.8
1           83733   Male  Non-Hispanic White   53   17.14  30.8    90.4
2           83734   Male  Non-Hispanic White   78   17.01  28.8    83.4
3           83741   Male  Non-Hispanic Black   22   16.54  28.0    76.6
4           83744   Male  Non-Hispanic Black   56   17.94  33.6   108.3

In [25]:
df["Height"] = df["Height"] * 10
df.head()

   Participant ID Gender      Race Ethnicity  Age  Height   BMI  Weight
0           83732   Male  Non-Hispanic White   62  1845.0  27.8    94.8
1           83733   Male  Non-Hispanic White   53  1714.0  30.8    90.4
2           83734   Male  Non-Hispanic White   78  1701.0  28.8    83.4
3           83741   Male  Non-Hispanic Black   22  1654.0  28.0    76.6
4           83744   Male  Non-Hispanic Black   56  1794.0  33.6   108.3

In [27]:
df["Height"].describe()

count    10457.000000
mean      1662.120685
std        101.272075
min       1297.000000
25%       1587.000000
50%       1659.000000
75%       1736.000000
max       2027.000000
Name: Height, dtype: float64

In [28]:
df["Height"] = df["Height"] / 10

In [29]:
df["Height"].describe()

count    10457.000000
mean       166.212068
std         10.127208
min        129.700000
25%        158.700000
50%        165.900000
75%        173.600000
max        202.700000
Name: Height, dtype: float64

In [32]:
df.dtypes

Participant ID      int64
Gender             object
Race Ethnicity     object
Age                 int64
Height            float64
BMI               float64
Weight            float64
dtype: object

In [33]:
df.head()

   Participant ID Gender      Race Ethnicity  Age  Height   BMI  Weight
0           83732   Male  Non-Hispanic White   62   184.5  27.8    94.8
1           83733   Male  Non-Hispanic White   53   171.4  30.8    90.4
2           83734   Male  Non-Hispanic White   78   170.1  28.8    83.4
3           83741   Male  Non-Hispanic Black   22   165.4  28.0    76.6
4           83744   Male  Non-Hispanic Black   56   179.4  33.6   108.3